/**
 * CASN API
 * CASN API (ASP.NET Core 2.1)
 *
 * OpenAPI spec version: 2.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CASNAppCoreModelsAppointmentDTO } from '../model/cASNAppCoreModelsAppointmentDTO';
import { CASNAppCoreModelsAppointmentType } from '../model/cASNAppCoreModelsAppointmentType';
import { CASNAppCoreModelsClinic } from '../model/cASNAppCoreModelsClinic';
import { CASNAppCoreModelsDriveCancelReason } from '../model/cASNAppCoreModelsDriveCancelReason';
import { CASNAppCoreModelsDriveStatus } from '../model/cASNAppCoreModelsDriveStatus';


import { Configuration }                                     from '../configuration';


export interface DefaultApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;


    /**
    * gets appointment by appointmentID
    * Search for existing appointment by appointmentIdentifier, return dispatcher-level details
    * @param appointmentID pass an appointmentIdentifier
    */
    getAppointmentByID(appointmentID: string, extraHttpRequestParams?: any): Observable<CASNAppCoreModelsAppointmentDTO>;

    /**
    * gets list of appointment types
    *
    */
    getAppointmentTypes(extraHttpRequestParams?: any): Observable<Array<CASNAppCoreModelsAppointmentType>>;

    /**
    * gets appointments with dispatcher-level details
    * Get all appointments within a default date range (possibly adjustable w/ query params). Appointments include details, e.g. exact location, available only to dispatchers.
    * @param startDate pass a startDate by which to filter
    * @param endDate pass an endDate by which to filter
    */
    getAppointments(startDate?: string, endDate?: string, extraHttpRequestParams?: any): Observable<Array<CASNAppCoreModelsAppointmentDTO>>;

    /**
    * gets list of clinics
    *
    */
    getClinics(extraHttpRequestParams?: any): Observable<Array<CASNAppCoreModelsClinic>>;

    /**
    * gets list of drive cancel reasons
    *
    */
    getDriveCancelReasons(extraHttpRequestParams?: any): Observable<Array<CASNAppCoreModelsDriveCancelReason>>;

    /**
    * gets list of drive statuses
    *
    */
    getDriveStatuses(extraHttpRequestParams?: any): Observable<Array<CASNAppCoreModelsDriveStatus>>;

    /**
    * gets list of badges combined with badges earned for the current user
    *
    */
    getBadges(extraHttpRequestParams?: any): Observable<Array<any>>;

}
