/**
 * CASN API
 * This is a test CASN API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AllAppointments } from '../model/allAppointments.model';
import { AppointmentDTO } from '../model/appointmentDTO.model';
import { Body } from '../model/body.model';
import { DriverDrive } from '../model/driverDrive.model';


import { Configuration }                                     from '../configuration';


export interface DriverServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * applies a volunteer for a drive
    * Adds a volunteer drive application
    * @param body 
    */
    addDriveApplicant(body?: Body, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * gets appointments with driver-level details
    * Get all appointments within a default date range (possibly adjustable w/ query params). Appointments DO NOT include details, e.g. exact location, available only to dispatchers. 
    * @param startDate pass a startDate by which to filter
    * @param endDate pass an endDate by which to filter
    */
    getAllAppointmentsForDriver(startDate?: string, endDate?: string, extraHttpRequestParams?: any): Observable<AllAppointments>;

    /**
    * gets appointment by appointmentID
    * Search for existing appointment by appointmentIdentifier, return driver-level details 
    * @param appointmentID pass an appointmentIdentifier
    */
    getAppointmentForDriverByID(appointmentID: string, extraHttpRequestParams?: any): Observable<AppointmentDTO>;

    /**
    * gets applied-for and approved drives for the current user
    * 
    */
    getMyDrives(extraHttpRequestParams?: any): Observable<Array<DriverDrive>>;

}
