/**
 * CASN API
 * CASN API (ASP.NET Core 2.1)
 *
 * OpenAPI spec version: 2.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CASNAppCoreModelsBody } from '../model/cASNAppCoreModelsBody';
import { CASNAppCoreModelsDriverDrive } from '../model/cASNAppCoreModelsDriverDrive';


import { Configuration }                                     from '../configuration';
import { CASNAppCoreModelsAppointmentDTO } from '../model/cASNAppCoreModelsAppointmentDTO';


export interface DriverApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;


    /**
    * applies a volunteer for a drive
    * Adds a volunteer drive application
    * @param body
    */
    addDriveApplicant(body?: CASNAppCoreModelsBody, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * unapplies a volunteer for a drive (if not already approved)
    * Removes a volunteer drive application
    * @param body
    */
    removeDriveApplicant(body?: CASNAppCoreModelsBody, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * gets applied-for and approved drives for the current user
    *
    */
    getMyDrives(extraHttpRequestParams?: any): Observable<Array<CASNAppCoreModelsAppointmentDTO>>;

}
