#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore CASNApp.API/CASNApp.API/ && \
    dotnet build CASNApp.API/CASNApp.API/ && \
    echo "Now, run the following to start the project: dotnet run -p CASNApp.API/CASNApp.API/CASNApp.API.csproj --launch-profile web"
