CREATE TABLE [dbo].[MessageLog]
(
    [Id] INT NOT NULL IDENTITY(1,1),
    [FromPhone] NVARCHAR(20) NOT NULL,
    [ToPhone] NVARCHAR(20) NOT NULL,
    [Subject] NVARCHAR(500) NULL,
    [Body] NVARCHAR(2000) NOT NULL,
    [DateSent] DATETIME NOT NULL CONSTRAINT [DF_MessageLog_DateSent] DEFAULT GETUTCDATE(),
    CONSTRAINT [PK_MessageLog] PRIMARY KEY CLUSTERED ([Id] ASC)
)
GO
CREATE NONCLUSTERED INDEX [IX_MessageLog_DateSent] ON [dbo].[MessageLog] ([DateSent] ASC)
WITH (PAD_INDEX=OFF,SORT_IN_TEMPDB=ON,ONLINE=OFF,STATISTICS_NORECOMPUTE=OFF,IGNORE_DUP_KEY=OFF,ALLOW_ROW_LOCKS=ON,ALLOW_PAGE_LOCKS=ON)
