CREATE TABLE [dbo].[State]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
    [IsActive] BIT NOT NULL CONSTRAINT [DF_State_IsActive] DEFAULT (0x01),
    [Created] DATETIME NOT NULL CONSTRAINT [DF_State_Created] DEFAULT (GETUTCDATE()),
    [Updated] DATETIME NULL,
	CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED
	(
	    [Id] ASC
	),
	CONSTRAINT [UQ_State_Name] UNIQUE ([Name])
)
