-- MySQL Script generated by MySQL Workbench
-- Mon Feb 18 20:58:03 2019
-- Model: casn-app data model    Version: 0.02
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema casn-app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casn-app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casn-app` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `casn-app` ;

-- -----------------------------------------------------
-- Table `casn-app`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`volunteer` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `civiContactId` INT(10) UNSIGNED NOT NULL,
  `firstName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lastName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `mobilePhone` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `googleAccount` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `googleIdentityToken` MEDIUMTEXT NULL,
  `isDriver` BIT(1) NOT NULL,
  `isDispatcher` BIT(1) NOT NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `casn-app`.`caller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`caller` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `civiContactId` INT(10) UNSIGNED NOT NULL,
  `callerIdentifier` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `firstName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lastName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `phone` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `isMinor` BIT(1) NOT NULL,
  `preferredLanguage` VARCHAR(25) NOT NULL,
  `preferredContactMethod` TINYINT(1) NOT NULL COMMENT '0 = Reserved, 1 = Text, 2 = Phone, 3 = Email',
  `note` VARCHAR(500) NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `casn-app`.`clinic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`clinic` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `civiContactId` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(30) NOT NULL,
  `postalCode` VARCHAR(10) NOT NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `casn-app`.`appointmenttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`appointmenttype` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `appointmentType_name` ON `casn-app`.`appointmenttype` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `casn-app`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`appointment` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dispatcherId` INT(10) UNSIGNED NOT NULL,
  `callerId` INT(10) UNSIGNED NOT NULL,
  `clinicId` INT(10) UNSIGNED NOT NULL,
  `pickupLocationVague` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `dropoffLocationVague` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `appointmentDate` DATETIME NOT NULL,
  `appointmentTypeId` INT(10) UNSIGNED NOT NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_appointment_DispatcherId`
    FOREIGN KEY (`dispatcherId`)
    REFERENCES `casn-app`.`volunteer` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_appointment_CallerId`
    FOREIGN KEY (`callerId`)
    REFERENCES `casn-app`.`caller` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_appointment_clinicId`
    FOREIGN KEY (`clinicId`)
    REFERENCES `casn-app`.`clinic` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_appointment_appointmentTypeId`
    FOREIGN KEY (`appointmentTypeId`)
    REFERENCES `casn-app`.`appointmenttype` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_appointment_DispatcherId_idx` ON `casn-app`.`appointment` (`dispatcherId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_appointment_CallerId_idx` ON `casn-app`.`appointment` (`callerId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_appointment_clinicId_idx` ON `casn-app`.`appointment` (`clinicId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_appointment_appointmentTypeId_idx` ON `casn-app`.`appointment` (`appointmentTypeId` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `casn-app`.`drive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`drive` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `appointmentId` INT(10) UNSIGNED NOT NULL,
  `direction` TINYINT(1) UNSIGNED NOT NULL COMMENT '0 = Reserved, 1 = ToClinic, 2 = FromClinic',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 = Open, 1 = Pending, 2 = Approved',
  `driverId` INT(10) UNSIGNED NULL DEFAULT NULL,
  `startAddress` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `startCity` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `startState` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `startPostalCode` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endAddress` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endCity` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endState` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endPostalCode` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `approved` DATETIME NULL,
  `approvedBy` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_drive_AppointmentId`
    FOREIGN KEY (`appointmentId`)
    REFERENCES `casn-app`.`appointment` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_drive_DriverId`
    FOREIGN KEY (`driverId`)
    REFERENCES `casn-app`.`volunteer` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_drive_ApprovedBy`
    FOREIGN KEY (`approvedBy`)
    REFERENCES `casn-app`.`volunteer` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_drive_AppointmentId_idx` ON `casn-app`.`drive` (`appointmentId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_drive_DriverId_idx` ON `casn-app`.`drive` (`driverId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_drive_ApprovedBy_idx` ON `casn-app`.`drive` (`approvedBy` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `casn-app`.`volunteer_drive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`volunteer_drive` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `volunteerId` INT(10) UNSIGNED NOT NULL,
  `driveId` INT(10) UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_volunteer_drive_DriveId`
    FOREIGN KEY (`driveId`)
    REFERENCES `casn-app`.`drive` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_volunteer_drive_VolunteerId`
    FOREIGN KEY (`volunteerId`)
    REFERENCES `casn-app`.`volunteer` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'XRef table to associate Volunteers (drivers) and the Drives for which they have applied.';

SHOW WARNINGS;
CREATE INDEX `fk_volunteer_drive_VolunteerId_idx` ON `casn-app`.`volunteer_drive` (`volunteerId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_volunteer_drive_DriveId_idx` ON `casn-app`.`volunteer_drive` (`driveId` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
