-- MySQL Script generated by MySQL Workbench
-- Sat Jun 23 15:00:00 2018
-- Model: casn-app data model    Version: 0.02
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema casn-app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casn-app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casn-app` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `casn-app` ;

-- -----------------------------------------------------
-- Table `casn-app`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`volunteer` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CiviContactId` INT(10) UNSIGNED NOT NULL,
  `FirstName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `LastName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `MobilePhone` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `GoogleAccount` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `IsDriver` BIT(1) NOT NULL,
  `IsDispatcher` BIT(1) NOT NULL,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `IsActive` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `casn-app`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`patient` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CiviContactId` INT(10) UNSIGNED NOT NULL,
  `PatientIdentifier` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `FirstName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `LastName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Phone` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `IsMinor` BIT(1) NOT NULL,
  `PreferredLanguage` VARCHAR(25) NOT NULL,
  `PreferredContactMethod` TINYINT(1) NOT NULL COMMENT '0 = Reserved, 1 = Text, 2 = Phone, 3 = Email',
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `casn-app`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`appointment` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DispatcherId` INT(10) UNSIGNED NOT NULL,
  `PatientId` INT(10) UNSIGNED NOT NULL,
  `ClinicId` INT(10) UNSIGNED NOT NULL,
  `PickupLocationVague` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `DropoffLocationVague` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `fk_appointment_DispatcherId_idx` (`DispatcherId` ASC),
  INDEX `fk_appointment_PatientId_idx` (`PatientId` ASC),
  CONSTRAINT `fk_appointment_DispatcherId`
    FOREIGN KEY (`DispatcherId`)
    REFERENCES `casn-app`.`volunteer` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_appointment_PatientId`
    FOREIGN KEY (`PatientId`)
    REFERENCES `casn-app`.`patient` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `casn-app`.`drive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`drive` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AppointmentId` INT(10) UNSIGNED NOT NULL,
  `Direction` TINYINT(1) UNSIGNED NOT NULL COMMENT '0 = Reserved, 1 = ToClinic, 2 = FromClinic',
  `DriverId` INT(10) UNSIGNED NULL DEFAULT NULL,
  `StartAddress` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `StartCity` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `StartState` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `StartPostalCode` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `EndAddress` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `EndCity` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `EndState` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `EndPostalCode` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `fk_drive_AppointmentId_idx` (`AppointmentId` ASC),
  INDEX `fk_drive_DriverId_idx` (`DriverId` ASC),
  CONSTRAINT `fk_drive_AppointmentId`
    FOREIGN KEY (`AppointmentId`)
    REFERENCES `casn-app`.`appointment` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_drive_DriverId`
    FOREIGN KEY (`DriverId`)
    REFERENCES `casn-app`.`volunteer` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `casn-app`.`volunteer_drive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casn-app`.`volunteer_drive` (
  `Id` INT(10) UNSIGNED NOT NULL,
  `VolunteerId` INT(10) UNSIGNED NOT NULL,
  `DriveId` INT(10) UNSIGNED NOT NULL,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `IsActive` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`Id`),
  INDEX `fk_volunteer_drive_VolunteerId_idx` (`VolunteerId` ASC),
  INDEX `fk_volunteer_drive_DriveId_idx` (`DriveId` ASC),
  CONSTRAINT `fk_volunteer_drive_DriveId`
    FOREIGN KEY (`DriveId`)
    REFERENCES `casn-app`.`drive` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_volunteer_drive_VolunteerId`
    FOREIGN KEY (`VolunteerId`)
    REFERENCES `casn-app`.`volunteer` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'XRef table to associate Volunteers (drivers) and the Drives for which they have applied.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
