/**
 * CASN API
 * This is a test CASN API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Caller {
    readonly id?: number;
    readonly civiContactId?: number;
    callerIdentifier: string;
    firstName: string;
    lastName: string;
    phone: string;
    isMinor: boolean;
    preferredLanguage: string;
    preferredContactMethod: number;
    readonly created?: Date;
    readonly updated?: Date;
}
