/**
 * CASN API
 * CASN API (ASP.NET Core 2.1)
 *
 * OpenAPI spec version: 2.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CASNAppCoreModelsCaller { 
    id?: number;
    civiContactId?: number;
    callerIdentifier: string;
    firstName: string;
    lastName?: string;
    phone: string;
    isMinor: boolean;
    preferredLanguage: string;
    preferredContactMethod: number;
    note?: string;
    created?: Date;
    updated?: Date;
}
