/**
 * CASN API
 * CASN API (ASP.NET Core 2.1)
 *
 * OpenAPI spec version: 2.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CASNAppCoreModelsAppointment } from './cASNAppCoreModelsAppointment';
import { CASNAppCoreModelsDrive } from './cASNAppCoreModelsDrive';
import { CASNAppCoreModelsDriveBuddy } from './cASNAppCoreModelsDriveBuddy'


export interface CASNAppCoreModelsAppointmentDTO {
    appointment?: CASNAppCoreModelsAppointment;
    driveTo?: CASNAppCoreModelsDrive;
    driveFrom?: CASNAppCoreModelsDrive;
    driveBuddy?: CASNAppCoreModelsDriveBuddy;
}
