/**
 * CASN API
 * CASN API (ASP.NET Core 2.1)
 *
 * OpenAPI spec version: 2.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CASNAppCoreModelsAppointment { 
    id?: number;
    dispatcherId: number;
    callerId: number;
    callerIdentifier?: string;
    callerNote?: string;
    clinicId: number;
    pickupLocationVague?: string;
    pickupVagueLatitude?: number;
    pickupVagueLongitude?: number;
    dropoffLocationVague?: string;
    dropoffVagueLatitude?: number;
    dropoffVagueLongitude?: number;
    appointmentDate: Date;
    appointmentTypeId: number;
    appointmentType?: string;
    created?: Date;
    updated?: Date;
}
