/**
 * CASN API
 * CASN API (ASP.NET Core 2.1)
 *
 * OpenAPI spec version: 2.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CASNAppCoreModelsVolunteerDrive { 
    id?: number;
    volunteerId?: number;
    firstName?: string;
    lastName?: string;
    mobilePhone?: string;
    driveId?: number;
    created?: Date;
    updated?: Date;
}
