/**
 * CASN API
 * CASN API (ASP.NET Core 2.1)
 *
 * OpenAPI spec version: 2.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CASNAppCoreModelsDriverDrive {
    id: number;
    volunteerDriveId: number;
    appointmentId: number;
    appointmentTypeId: number;
    serviceProviderId: number;
    appointmentDate: Date;
    direction: number;
    isApproved: boolean;
    startLocation?: string;
    startLatitude?: number;
    startLongitude?: number;
    endLocation?: string;
    endLatitude?: number;
    endLongitude?: number;
    callerIdentifier: string;
    callerName?: string;
    callerNote?: string;
}
