/**
 * CASN API
 * This is a test CASN API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Drive {
    readonly id?: number;
    appointmentId: number;
    /**
     * 1 = toClinic, 2 = fromClinic
     */
    direction: number;
    driverId?: number;
    startAddress: string;
    startCity: string;
    startState: string;
    startPostalCode: string;
    endAddress: string;
    endCity: string;
    endState: string;
    endPostalCode: string;
    readonly created?: Date;
    readonly updated?: Date;
    readonly approved?:	Date;
    approvedById?: number;
    cancelReasonId?: number;
    cancelReason?: string;
}
