/**
 * CASN API
 * This is a test CASN API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: katie@clinicaccess.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VolunteerDrive { 
    id?: number;
    volunteerId?: number;
    firstName?: string;
    lastName?: string;
    mobilePhone?: string;
    driveId?: number;
    readonly created?: Date;
    readonly updated?: Date;
}
