/*
 * CASN API
 *
 * This is a test CASN API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: katie@clinicaccess.org
 * Generated by: https://openapi-generator.tech
 */

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CASNApp.API.Attributes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace CASNApp.API.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class DefaultApiController : Controller
    {
        private readonly Entities.casn_appContext dbContext;

        public DefaultApiController(Entities.casn_appContext dbContext)
        {
            this.dbContext = dbContext;
        }

        /// <summary>
        /// gets list of clinics
        /// </summary>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("api/clinic")]
        [ValidateModelState]
        [SwaggerOperation("GetClinics")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Models.Clinic>), description: "successful operation")]
        public virtual async Task<IActionResult> GetClinics()
        {
            var clinics = await dbContext.Clinic
                .AsNoTracking()
                .Select(c => new Models.Clinic(c))
                .ToListAsync();

            return new ObjectResult(clinics);
        }
    }
}
